apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260506-190231-s5s4fqfwzrxi-service
spec:
  selector:
    app: enterprise-system-20260506-190231-s5s4fqfwzrxi
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
